-- Create films table
CREATE TABLE IF NOT EXISTS public.films (
    id          serial PRIMARY KEY,
    code        char(5),
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);

-- Create distributors table
CREATE TABLE IF NOT EXISTS public.distributors (
     did     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name    varchar(40) NOT NULL CHECK (name <> ''),
     film_id integer,
     FOREIGN KEY (film_id) REFERENCES films (id)
);